# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: Headers Enricher

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/lucho00cuba/headers-enricher

# A brief description of what your plugin is doing.
summary: Generate and compose HTTP headers from request data, response data, and environment variables.

# Medias associated to the plugin (optional)
iconPath: assets/icon.png
# bannerPath: assets/banner.png

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  allowedEnv:
    - NODE_NAME
    - HOSTNAME
  headers:
    request:
      X-Request-Id:
        from: uuid
      X-Demo-User:
        from: request.header
        name: XAuthUser
        default: anonymous
      X-Demo-Template:
        from: template
        value: '[[ .Method ]]-[[ .Path ]]-[[ .Env.NODE_NAME ]]'
      X-Demo-Node-Name:
        from: env
        name: NODE_NAME
        default: unknown-node
    response:
      X-Demo-Plugin:
        from: literal
        value: headers-enricher
      X-Demo-Response:
        from: template
        value: '[[ .StatusCode ]]-[[ .Host ]]'
